version: '3.7'

services:
  php_fpm:
    build:
      dockerfile: ./.docker/php/Dockerfile
      context: ./
    restart: unless-stopped
    volumes:
      - ./vendor:/app/vendor
      - ./classes:/app/classes
      - ./public:/app/public
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./.docker/php/conf.d/service.dev.ini:/usr/local/etc/php/conf.d/service.ini
      - php_socket:/var/run/php

  nginx:
    build:
      context: ./
      dockerfile: ./.docker/nginx/Dockerfile
      target: dev
    ports:
      - "8000:80"
    depends_on:
      - php_fpm
    volumes:
      - php_socket:/var/run/php
      - ./:/app

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  php_socket:
    driver: local
  postgres:
